### ISSUE TITLE
Atualização para o IRPF2021

### ISSUE THREAD

**Issue by Beleren** [andresmrm/docker-irpf#9]
Oi, estou tentando atualizar o projeto para a [nova versão do IRPF](http://downloadirpf.receita.fazenda.gov.br/irpf/2021/irpf/arquivos/IRPF2021-1.1.zip) e encontrei os seguintes problemas:

1. O novo software aparentemente exige a versão 11 do JDK;
![image](https://user-images.githubusercontent.com/11512170/110042263-4aabcd80-7d24-11eb-93f2-46358506b541.png)

2. A imagem atualizada( `openjdk:17-jdk-alpine3.12`) não contém todas as dependências para utilizar o software;
![image](https://user-images.githubusercontent.com/11512170/110041837-8a25ea00-7d23-11eb-892f-99fb1f6bf5e2.png)

Tentei atualizar o comando de instalação para `apk add --no-cache wget ttf-dejavu libxext libxrender` mas sem sucesso.

As alterações estão no [meu fork](https://github.com/Beleren/docker-irpf)

**Comment by jersonb** [comment]
Seria bem legal não precisar instalar e configurar o JAVA só pra fazer a declaração, vou tentar fazer também!

**Comment by andresmrm** [comment]
Dei uma olhada e também não consegui uma solução fácil com Alpine. Estou sem tempo para continuar tentando, então talvez o mais fácil seja usar um dos vários outros projetos por aí: https://github.com/search?q=docker+irpf
Ainda não testei nenhum, mais há alguns atualizados recentemente.

**Comment by Beleren** [comment]
Testei o esse repo e parece funcionar: https://github.com/geovanisouza92/irpf-docker
